environment:
  type: provided
  db: postgres

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=auth}
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false